#info
info:
  app:
    name: ${spring.application.name}
    instance: ${eureka.instance.instance-id}
#eureka
eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: true